### Signup
###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name": "Ahmed Mohamed",
    "email": "ahmed128@example.com",
    "password": "12345678",
    "phone": "01234567890",
    "profileImage":"https://s3-figma-plugin-images-production-sig.figma.com/plugins/carousel/img/1164118094004004837/1b119bd57c4e157c09366371efd143558a659a15?Expires=1749427200&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=pd~OM4IgxPKEDvqLWLgPsqM32qgqzkVRBA9Q8dlmPtnx5xZmFoTds3xG2mogl3Dto3I5RxgV6T1igNp80QwR6bKbhWN7DfcvfEHfgqUpA00GHvdgMvsfcp8scp1YR1-UnUc-hGeWuFJ-A0ra-VWx7uF1gnvF0JwLmD-grfYrfLQA1LGsjrneEwRT~s3bX8cYKtC63RU4Ov~79m-NkwRABUNKfSgzGLHwmnOgEMOOLMiEnMPwdT5SEgfQ-waMLqkKHmLkxL~CTl31QNgXnA79qjK1GxcJ8Il~NhunGuxYTN5G~MQQ7horyBD42KLpEa2okXE82DJNaNYkGU4P1WCAdA__"
}
###
### Login

POST http://localhost:5000/auth/auth/login
Content-Type: application/json

{
    "email": "ahmed@example.com",
    "password": "12345678"
}
###
/// create Place
POST http://localhost:5000/place
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Mzg0ZDllNTQ5OTJiMzExZmZhZGYzYSIsImlhdCI6MTc0OTk4NzI3OCwiZXhwIjoxNzU3NzYzMjc4fQ.ecGvJyVTkrIXRPIK1uI0gku4iP6R256-C01c4NXjQKY

{
  "name": "Pyramids of Giza",
  "city": "Giza",
  "description": "The last remaining wonder of the ancient world.",
  "images": [
    "https://example.com/pyramids1.jpg",
    "https://example.com/pyramids2.jpg"
  ],
  "category": "Historical",
  "price": 100,
  "location": {
    "type": "Point",
    "coordinates": [31.1342, 29.9792]
  }
}

###
// create trip
POST http://localhost:5000/trip/createTrip
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Mzg0ZDllNTQ5OTJiMzExZmZhZGYzYSIsImlhdCI6MTc1MDAwODgyNywiZXhwIjoxNzU3Nzg0ODI3fQ.sH8JjngtdL8hQlfLss6kUm8JRu3iLL79CckZWFv7vyU

{
  "selectedPlaces": [
    "684a601557826106ff05a799",
    "684a601557826106ff05a79a",
    "684a601557826106ff05a79b"
  ]
}
###
  // get my trips
GET http://localhost:5000/trip/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Mzg0ZDllNTQ5OTJiMzExZmZhZGYzYSIsImlhdCI6MTc1MDAwODgyNywiZXhwIjoxNzU3Nzg0ODI3fQ.sH8JjngtdL8hQlfLss6kUm8JRu3iLL79CckZWFv7vyU


### Search places by name and city
GET http://localhost:5000/places/searchPlace?name=pyramid
Content-Type: application/json

###

### Search places by category only
GET http://localhost:5000/places/searchPlace?name=pyramid&city=Giza
Content-Type: application/json
###

### Search all places (بدون فلاتر)
GET http://localhost:5000/places/searchPlace
Content-Type: application/json

### Create new driver (admin only)
POST http://localhost:5000/driver
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Mzg0ZDllNTQ5OTJiMzExZmZhZGYzYSIsImlhdCI6MTc1MDAwODgyNywiZXhwIjoxNzU3Nzg0ODI3fQ.sH8JjngtdL8hQlfLss6kUm8JRu3iLL79CckZWFv7vyU

{
  "name": "Mohamed Driver",
  "phone": "01123456789",
  "hasCar": true,
  "carType": "Toyota Corolla",
  "pricePerHour": 150,
  "profileImage": "https://example.com/driver.jpg",
  "isAvailable": true
}

### Create new review for a place (user only)
POST http://localhost:5000/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Mzg0ZDllNTQ5OTJiMzExZmZhZGYzYSIsImlhdCI6MTc1MDAwODgyNywiZXhwIjoxNzU3Nzg0ODI3fQ.sH8JjngtdL8hQlfLss6kUm8JRu3iLL79CckZWFv7vyU

{
  "placeId": "684a601557826106ff05a799",
  "rating": 5,
  "comment": "Amazing place, highly recommended!"
}